name: whats_app_clone
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.1
  get_it: ^8.2.0
  go_router: ^16.2.4
  intl_phone_field: ^3.2.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/svgs/
    - assets/images/

# 👇 ضع إعدادات الأيقونة هنا (خارج flutter:)
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter_assets:
  assets_path: assets/images/svgs/
  output_path: lib/core/utils/
  filename: app_images.dart
  field_prefix: null
