// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmdEtGd3k7Cf-275oCwE9IXPDyYiN1M9E',
    appId: '1:1088949057873:web:888743a77688cd3ec67b70',
    messagingSenderId: '1088949057873',
    projectId: 'fx-chat-f14ee',
    authDomain: 'fx-chat-f14ee.firebaseapp.com',
    storageBucket: 'fx-chat-f14ee.firebasestorage.app',
    measurementId: 'G-H439W7GZJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCijxrf0_C0mHAUUCOkee03i9cVmQq0SMg',
    appId: '1:1088949057873:android:bb386cc92add1c94c67b70',
    messagingSenderId: '1088949057873',
    projectId: 'fx-chat-f14ee',
    storageBucket: 'fx-chat-f14ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLGbqg4UHAdAxAJocJadJubDG-NtB-yU4',
    appId: '1:1088949057873:ios:5d83bfa4d999fa1ec67b70',
    messagingSenderId: '1088949057873',
    projectId: 'fx-chat-f14ee',
    storageBucket: 'fx-chat-f14ee.firebasestorage.app',
    iosBundleId: 'com.example.whatsAppClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLGbqg4UHAdAxAJocJadJubDG-NtB-yU4',
    appId: '1:1088949057873:ios:5d83bfa4d999fa1ec67b70',
    messagingSenderId: '1088949057873',
    projectId: 'fx-chat-f14ee',
    storageBucket: 'fx-chat-f14ee.firebasestorage.app',
    iosBundleId: 'com.example.whatsAppClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCygSdoITLSOVaPhfX5mk09OoRc8pVE7HA',
    appId: '1:1088949057873:web:b00fe952049df4d4c67b70',
    messagingSenderId: '1088949057873',
    projectId: 'fx-chat-f14ee',
    authDomain: 'fx-chat-f14ee.firebaseapp.com',
    storageBucket: 'fx-chat-f14ee.firebasestorage.app',
    measurementId: 'G-5EKD0YGL77',
  );
}
